# Generated by Django 5.0.6 on 2024-05-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_num', models.CharField(max_length=10)),
                ('airport_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_end', to='airline.airport')),
                ('airport_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airport_start', to='airline.airport')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.plane')),
            ],
        ),
    ]
