# Generated by Django 5.0.6 on 2024-05-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0006_alter_customer_gender_flight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
