# Generated by Django 5.0.6 on 2024-05-29 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0008_booking_seats_route_duration_alter_plane_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='flight',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
