# Generated by Django 5.0.6 on 2024-05-29 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0009_flight_date_flight_price_flight_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='date',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='time',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_date',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='leaving_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='leaving_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
