# Generated by Django 5.0.6 on 2024-05-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0014_customer_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Miss', 'Miss')], max_length=4, null=True),
        ),
    ]
