# Generated by Django 5.0.6 on 2024-05-31 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0015_alter_customer_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
