# Generated by Django 5.0.6 on 2024-05-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0016_alter_plane_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='duration',
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
