# Generated by Django 5.0.6 on 2024-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0017_remove_route_duration_flight_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
