# Generated by Django 5.0.6 on 2024-06-01 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0018_alter_flight_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_date',
            new_name='arrival_date_utc',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='arrival_time',
            new_name='arrival_time_utc',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='leaving_date',
            new_name='leaving_date_utc',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='leaving_time',
            new_name='leaving_time_utc',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='route',
            name='flight_num',
        ),
        migrations.RemoveField(
            model_name='route',
            name='plane',
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_inbound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_inbound', to='airline.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_outbound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_outbound', to='airline.flight'),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_num',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='plane',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.plane'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airline.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='airline.route'),
        ),
    ]
