# Generated by Django 5.0.6 on 2024-06-01 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0020_alter_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
