# Generated by Django 5.0.6 on 2024-06-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0024_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
